name: bh_shared
description: "bh_shared package now rolled into flutter_callout package"
version: 3.0.0
repository: https://github.com/biancashouse/flutter_callouts
homepage: https://biancashouse.com
#publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

cider:
  link_template:
    tag: https://github.com/biancashouse/bh_shared/releases/tag/%tag% # initial release link template
    diff: https://github.com/biancashouse/bh_shared/compare/%from%...%to% # subsequent releases link template