name: bh_shared
description: "Bianca's House shared package"
version: 2.0.1
repository: https://github.com/biancashouse/bh_shared
homepage: https://biancashouse.com/bh_shared
#publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^8.0.0
  universal_platform: ^1.0.0+1
  device_info_plus: ^10.1.0
  path_provider: ^2.0.11
  image_network: ^2.5.1
  hydrated_bloc: ^9.0.0
  intl: ^0.19.0
  timeago: ^3.6.1
  go_router: ^14.1.4
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

cider:
  link_template:
    tag: https://github.com/biancashouse/bh_shared/releases/tag/%tag% # initial release link template
    diff: https://github.com/biancashouse/bh_shared/compare/%from%...%to% # subsequent releases link template
